spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/certificate_analysis?characterEncoding=utf-8
    username: root
    password: 333
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  backup-location: ./mysql_backup/