@startuml visualize_certification

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 证书信息统计页面
participant 证书信息统计控制器
participant 证书信息统计服务
participant 证书信息统计映射器
participant 数据库

用户 -> 证书信息统计页面: 填写统计表单
activate 证书信息统计页面

证书信息统计页面 -> 证书信息统计控制器: 发送查询字段
activate 证书信息统计控制器

证书信息统计控制器 -> 证书信息统计服务: 发送查询字段
activate 证书信息统计服务

证书信息统计服务 -> 证书信息统计映射器: 发送查询字段
activate 证书信息统计映射器

证书信息统计映射器 -> 数据库: 根据查询字段填充SQL语句
activate 数据库

数据库 -> 数据库: 查询数据
数据库 -> 证书信息统计映射器: 返回查询结果

deactivate 数据库
证书信息统计映射器 --> 证书信息统计服务: 返回查询结果
deactivate 证书信息统计映射器


证书信息统计服务 --> 证书信息统计控制器: 返回查询结果

deactivate 证书信息统计服务

证书信息统计控制器 --> 证书信息统计页面: 返回查询结果
deactivate 证书信息统计控制器

证书信息统计页面 --> 证书信息统计页面: 渲染查询表格和图像

@enduml