@startuml certification_statistic_export

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 证书信息统计页面
participant 证书信息统计控制器
participant 证书信息统计服务

activate 用户
用户 -> 证书信息统计页面: 选择导出数据和导出条件
activate 证书信息统计页面

证书信息统计页面 -> 证书信息统计控制器: 携带参数发送导出请求
activate 证书信息统计控制器

证书信息统计控制器 -> 证书信息统计控制器: 根据导出请求查询导出数据

证书信息统计控制器 -> 证书信息统计服务: 调用数据导出服务
activate 证书信息统计服务

证书信息统计服务 -> 证书信息统计服务: 生成Excel文件并写入response
证书信息统计服务 --> 证书信息统计页面: 开始下载Excel文件

deactivate 证书信息统计服务
deactivate 证书信息统计控制器

证书信息统计页面 --> 用户: Excel文件

deactivate 证书信息统计页面

@enduml