@startuml workspace

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

activate 用户
用户 -> 数据备份页面: 填写备份表单并提交

activate 数据备份页面
数据备份页面 -> 数据备份控制器: 数据备份表单

activate 数据备份控制器
数据备份控制器 -> 数据备份服务: 数据备份请求

activate 数据备份服务
数据备份服务 -> 数据备份映射器: 数据备份请求

activate 数据备份映射器
数据备份映射器 -> 数据库: 数据备份请求

activate 数据库 
数据库 -> 数据库: 数据备份

数据库 --> 数据备份映射器: 返回备份结果
deactivate 数据库

数据备份映射器 --> 数据备份服务: 返回备份结果
deactivate 数据备份映射器

数据备份服务 --> 数据备份控制器: 返回备份结果
deactivate 数据备份服务

数据备份控制器 --> 数据备份页面: 返回备份结果
deactivate 数据备份控制器

数据备份页面 --> 用户: 告知备份结果
deactivate 数据备份页面

@enduml