@startuml workspace

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

activate 用户
用户 -> 数据恢复页面: 恢复指定数据

activate 数据恢复页面
数据恢复页面 -> 数据恢复控制器: 数据恢复

activate 数据恢复控制器
数据恢复控制器 -> 数据恢复服务: 数据恢复

activate 数据恢复服务
数据恢复服务 -> 数据恢复映射器: 数据恢复

activate 数据恢复映射器
数据恢复映射器 -> 数据库: 数据恢复

activate 数据库 
数据库 -> 数据库: 读取文件进行数据恢复

数据库 -> 数据恢复映射器: 返回恢复结果
deactivate 数据库

数据恢复映射器 -> 数据恢复服务: 返回恢复结果
deactivate 数据恢复映射器

数据恢复服务 -> 数据恢复控制器: 返回恢复结果
deactivate 数据恢复服务

数据恢复控制器 -> 数据恢复页面: 返回恢复结果
deactivate 数据恢复控制器

数据恢复页面 -> 用户: 告知恢复结果
deactivate 数据恢复页面

@enduml