@startuml written_add

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 认定信息管理页面
participant 认定信息管理控制器

activate 用户
用户 -> 认定信息管理页面: 填写添加认定数据表单

activate 认定信息管理页面
认定信息管理页面 -> 认定信息管理页面: 表单校验失败

activate 认定信息管理页面 #1
认定信息管理页面 -> 用户: 重新填写表单
deactivate 认定信息管理页面 #1

认定信息管理页面 -> 认定信息管理控制器: 提交认定信息信息


activate 认定信息管理控制器
认定信息管理控制器 -> 认定信息管理控制器: 填充实体类并插入数据库

认定信息管理控制器 --> 认定信息管理页面: 返回添加结果
deactivate 认定信息管理控制器

认定信息管理页面 --> 用户: 显示添加结果



@enduml