@startuml written_import

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 面试成绩管理页面
participant 面试成绩管理控制器
participant 面试成绩管理服务

activate 用户
用户 -> 面试成绩管理页面: 上传Excel文件

activate 面试成绩管理页面
面试成绩管理页面 -> 面试成绩管理页面: 文件校验失败

activate 面试成绩管理页面 #1
面试成绩管理页面 --> 用户: 告知用户重新导入文件
deactivate 面试成绩管理页面 #1

面试成绩管理页面 -> 面试成绩管理控制器: 发送文件

activate 面试成绩管理控制器
面试成绩管理控制器 -> 面试成绩管理服务: 调用数据导入服务

activate 面试成绩管理服务
面试成绩管理服务 -> 面试成绩管理服务: 读取Excel文件并转换成实体类列表并插入数据库

面试成绩管理服务 --> 面试成绩管理控制器: 返回导入情况
deactivate 面试成绩管理服务

面试成绩管理控制器 --> 面试成绩管理页面: 返回导入情况
deactivate 面试成绩管理控制器

面试成绩管理页面 --> 用户: 返回导入情况
deactivate 面试成绩管理页面

@enduml