@startuml written_update

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 面试成绩管理页面
participant 面试成绩管理控制器

activate 用户
用户 -> 面试成绩管理页面: 填写修改成绩表单


activate 面试成绩管理页面
面试成绩管理页面 -> 面试成绩管理页面: 表单校验失败

activate 面试成绩管理页面 #1
面试成绩管理页面 --> 用户: 显示表单校验失败
deactivate 面试成绩管理页面 #1

面试成绩管理页面 -> 面试成绩管理控制器: 提交修改后的面试成绩信息

activate 面试成绩管理控制器
面试成绩管理控制器 -> 面试成绩管理控制器: 修改实体类并插入数据库

面试成绩管理控制器 --> 面试成绩管理页面: 返回修改结果
deactivate 面试成绩管理控制器

面试成绩管理页面 --> 用户: 显示修改结果

@enduml