@startuml dashboard

数据大屏 -> 数据大屏控制器: 登录请求
activate 数据大屏控制器

数据大屏控制器 -> 认定数据服务: 查询任教学科、最高学历、学位、性别分布、数据总数等统计数据
数据大屏控制器 -> 面试成绩数据服务: 查询最近年份面试等级、数据总数统计数据
数据大屏控制器 -> 笔试成绩数据服务: 查询数据总数统计数据

认定数据服务 -> 认定数据Mapper: 查询相关数据
面试成绩数据服务 -> 面试成绩数据Mapper: 查询相关数据
笔试成绩数据服务 -> 笔试成绩数据Mapper: 查询相关数据

认定数据Mapper -> 数据库: 查询数据
面试成绩数据Mapper -> 数据库: 查询数据
笔试成绩数据Mapper -> 数据库: 查询数据

数据库 -> 认定数据Mapper: 返回统计数据
数据库 -> 面试成绩数据Mapper: 返回统计数据
数据库 -> 笔试成绩数据Mapper: 返回统计数据


认定数据Mapper -> 认定数据服务: 返回数据
面试成绩数据Mapper -> 面试成绩数据服务: 返回数据
笔试成绩数据Mapper -> 笔试成绩数据服务: 返回数据

认定数据服务 -> 数据大屏控制器: 返回数据
面试成绩数据服务 -> 数据大屏控制器: 返回数据
笔试成绩数据服务 -> 数据大屏控制器: 返回数据

数据大屏控制器 --> 数据大屏: 整合并返回数据

deactivate 数据大屏控制器
deactivate 数据大屏

@enduml