@startuml workspace

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}


activate 前端页面
前端页面 -> Java后端: 数据分析请求

activate Java后端
Java后端 -> 操作系统: 调用Python脚本

activate 操作系统
操作系统 -> Python数据分析程序: 数据预测

activate Python数据分析程序
Python数据分析程序 -> Python数据分析程序: 数据预测

Python数据分析程序 --> 操作系统: 输出分析结果
deactivate Python数据分析程序

操作系统 --> Java后端: 输出数据预测结果
deactivate 操作系统

Java后端 --> 前端页面: 返回数据预测结果
deactivate Java后端

前端页面 -> 前端页面: 页面渲染

@enduml