@startuml written_add

participant 用户
participant 笔试成绩管理页面
participant 笔试成绩管理控制器


activate 用户
用户 -> 笔试成绩管理页面: 填写添加成绩表单
activate 笔试成绩管理页面

笔试成绩管理页面 -> 笔试成绩管理控制器: 提交笔试成绩信息
activate 笔试成绩管理控制器

笔试成绩管理控制器 -> 笔试成绩管理控制器: 填充实体类并插入数据库

笔试成绩管理控制器 -> 笔试成绩管理页面: 返回添加结果
deactivate 笔试成绩管理控制器

笔试成绩管理页面 -> 用户: 显示添加结果
deactivate 用户

@enduml