@startuml written_update

hide footbox
skinparam sequence {
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
}

participant 用户
participant 证书信息管理页面
participant 证书信息管理控制器

activate 用户
用户 -> 证书信息管理页面: 填写修改证书信息表单


activate 证书信息管理页面
证书信息管理页面 -> 证书信息管理页面: 表单校验失败

activate 证书信息管理页面 #1
证书信息管理页面 --> 用户: 显示表单校验失败
deactivate 证书信息管理页面 #1

证书信息管理页面 -> 证书信息管理控制器: 提交修改后的证书信息信息

activate 证书信息管理控制器
证书信息管理控制器 -> 证书信息管理控制器: 修改实体类并插入数据库

证书信息管理控制器 --> 证书信息管理页面: 返回修改结果
deactivate 证书信息管理控制器

证书信息管理页面 --> 用户: 显示修改结果

@enduml